{
  "abstract": [
    {
      "text": "A trace trap or invalid CPU instruction interrupted the process,",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "often because the process violated a requirement or timeout.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Xcode/documentation/Xcode",
        "doc://com.apple.Xcode/documentation/Xcode/debugging",
        "doc://com.apple.Xcode/documentation/Xcode/diagnosing-issues-using-crash-reports-and-device-logs",
        "doc://com.apple.Xcode/documentation/Xcode/understanding-the-exception-types-in-a-crash-report"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Xcode/documentation/Xcode/SIGTRAP_SIGILL"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "role": "article",
    "roleHeading": "Article",
    "title": "EXC_BREAKPOINT (SIGTRAP) and EXC_BAD_INSTRUCTION (SIGILL)"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A trace trap gives an attached debugger the chance to interrupt the process at a specific",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "point in its execution. On ARM processors, this appears as ",
              "type": "text"
            },
            {
              "code": "EXC_BREAKPOINT (SIGTRAP). ",
              "type": "codeVoice"
            },
            {
              "text": "On ",
              "type": "text"
            },
            {
              "code": "x86_64",
              "type": "codeVoice"
            },
            {
              "text": " processors, this appears as ",
              "type": "text"
            },
            {
              "code": "EXC_BAD_INSTRUCTION (SIGILL)",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The Swift runtime uses trace traps for specific types of unrecoverable errors—see",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Xcode/documentation/Xcode/addressing-crashes-from-swift-runtime-errors",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for information on those errors.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Some lower-level libraries, such as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Dispatch",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ",",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "trap the process with this exception upon encountering an unrecoverable error, and",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "log additional information about the error in the ",
              "type": "text"
            },
            {
              "code": "Additional Diagnostic Information",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "section of the crash report. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Xcode/documentation/Xcode/examining-the-fields-in-a-crash-report#Diagnostic-messages",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "for information about those messages.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you want to use the same technique in your own code for unrecoverable errors,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Swift/fatalError(_:file:line:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function in Swift,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "or the ",
              "type": "text"
            },
            {
              "code": "__builtin_trap()",
              "type": "codeVoice"
            },
            {
              "text": " function in C. These functions allow the system to generate a crash",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "report with thread backtraces that show how you reached the unrecoverable error.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "An illegal CPU instruction means",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the program’s executable contains an instruction",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "that the processor doesn’t implement or can’t execute.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For example, the following program",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "tries to perform the CPU instruction ",
              "type": "text"
            },
            {
              "code": "0x00000001",
              "type": "codeVoice"
            },
            {
              "text": ",",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "which isn’t a valid instruction on Apple silicon:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "#include <stdint.h>",
            "",
            "int main(int argc, char **argv) {",
            "    static const uint32_t sTest[] = {",
            "        0x00000001,",
            "    };",
            "    typedef void (*FuncPtr)(void);",
            "    FuncPtr f = (FuncPtr) sTest;",
            "    f();",
            "    return 0;",
            "}"
          ],
          "syntax": "c",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Xcode-PageImage-card.png": {
      "alt": "The Xcode logo on a blue gradient background.",
      "identifier": "Xcode-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/cc63eacd8f7f660388b46204d1d9bbcb/Xcode-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/62dba87d5f60ec96eb48882c9dff86d8/Xcode-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.Xcode/documentation/Xcode": {
      "abstract": [
        {
          "text": "Build, test, and submit your app with Apple’s integrated development environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode",
      "images": [
        {
          "identifier": "Xcode-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collection",
      "title": "Xcode",
      "type": "topic",
      "url": "/documentation/xcode"
    },
    "doc://com.apple.Xcode/documentation/Xcode/EXC_ARITHMETIC": {
      "abstract": [
        {
          "text": "An arithmetic problem terminated the process,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "often because of division by zero or a floating-point error.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/EXC_ARITHMETIC",
      "kind": "article",
      "role": "article",
      "title": "EXC_ARITHMETIC",
      "type": "topic",
      "url": "/documentation/xcode/exc_arithmetic"
    },
    "doc://com.apple.Xcode/documentation/Xcode/EXC_BAD_ACCESS": {
      "abstract": [
        {
          "text": "A bad access to memory terminated the process.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/EXC_BAD_ACCESS",
      "kind": "article",
      "role": "article",
      "title": "EXC_BAD_ACCESS",
      "type": "topic",
      "url": "/documentation/xcode/exc_bad_access"
    },
    "doc://com.apple.Xcode/documentation/Xcode/EXC_CRASH": {
      "abstract": [
        {
          "text": "The process crashed.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/EXC_CRASH",
      "kind": "article",
      "role": "article",
      "title": "EXC_CRASH",
      "type": "topic",
      "url": "/documentation/xcode/exc_crash"
    },
    "doc://com.apple.Xcode/documentation/Xcode/EXC_GUARD": {
      "abstract": [
        {
          "text": "The process violated a guarded resource protection, often related to file descriptors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/EXC_GUARD",
      "kind": "article",
      "role": "article",
      "title": "EXC_GUARD",
      "type": "topic",
      "url": "/documentation/xcode/exc_guard"
    },
    "doc://com.apple.Xcode/documentation/Xcode/EXC_RESOURCE": {
      "abstract": [
        {
          "text": "The operating system stopped the process",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "because the process exceeded a limit on resource consumption,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "like CPU time or memory.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/EXC_RESOURCE",
      "kind": "article",
      "role": "article",
      "title": "EXC_RESOURCE",
      "type": "topic",
      "url": "/documentation/xcode/exc_resource"
    },
    "doc://com.apple.Xcode/documentation/Xcode/SIGABRT": {
      "abstract": [
        {
          "text": "The process terminated because it received an abort signal.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/SIGABRT",
      "kind": "article",
      "role": "article",
      "title": "EXC_CRASH (SIGABRT)",
      "type": "topic",
      "url": "/documentation/xcode/sigabrt"
    },
    "doc://com.apple.Xcode/documentation/Xcode/SIGBUS": {
      "abstract": [
        {
          "text": "A bus error terminated the process,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "often because the process tried to",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "access a misaligned or invalid address in memory,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "or due to a pointer authentication failure.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/SIGBUS",
      "kind": "article",
      "role": "article",
      "title": "EXC_BAD_ACCESS (SIGBUS)",
      "type": "topic",
      "url": "/documentation/xcode/sigbus"
    },
    "doc://com.apple.Xcode/documentation/Xcode/SIGKILL": {
      "abstract": [
        {
          "text": "The operating system terminated the process,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "often because a background task violated a requirement,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "device resources were limited,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "or the user force quit the app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/SIGKILL",
      "kind": "article",
      "role": "article",
      "title": "EXC_CRASH (SIGKILL)",
      "type": "topic",
      "url": "/documentation/xcode/sigkill"
    },
    "doc://com.apple.Xcode/documentation/Xcode/SIGQUIT": {
      "abstract": [
        {
          "text": "Another processes terminated the process,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "often because the process violated a requirement or timeout.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/SIGQUIT",
      "kind": "article",
      "role": "article",
      "title": "EXC_CRASH (SIGQUIT)",
      "type": "topic",
      "url": "/documentation/xcode/sigquit"
    },
    "doc://com.apple.Xcode/documentation/Xcode/SIGSEGV": {
      "abstract": [
        {
          "text": "A memory segmentation fault terminated the process,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "often because the process tried to",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "access an invalid or out-of-bounds address in memory.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/SIGSEGV",
      "kind": "article",
      "role": "article",
      "title": "EXC_BAD_ACCESS (SIGSEGV)",
      "type": "topic",
      "url": "/documentation/xcode/sigsegv"
    },
    "doc://com.apple.Xcode/documentation/Xcode/SIGSYS": {
      "abstract": [
        {
          "text": "A bad argument to a system call terminated the process.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/SIGSYS",
      "kind": "article",
      "role": "article",
      "title": "EXC_CRASH (SIGSYS)",
      "type": "topic",
      "url": "/documentation/xcode/sigsys"
    },
    "doc://com.apple.Xcode/documentation/Xcode/SIGTERM": {
      "abstract": [
        {
          "text": "A software termination signal terminated the process.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/SIGTERM",
      "kind": "article",
      "role": "article",
      "title": "EXC_CRASH (SIGTERM)",
      "type": "topic",
      "url": "/documentation/xcode/sigterm"
    },
    "doc://com.apple.Xcode/documentation/Xcode/addressing-crashes-from-swift-runtime-errors": {
      "abstract": [
        {
          "text": "Identify the signs of a Swift runtime error, and address the crashes runtime errors",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "cause.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/addressing-crashes-from-swift-runtime-errors",
      "kind": "article",
      "role": "article",
      "title": "Addressing crashes from Swift runtime errors",
      "type": "topic",
      "url": "/documentation/xcode/addressing-crashes-from-swift-runtime-errors"
    },
    "doc://com.apple.Xcode/documentation/Xcode/debugging": {
      "abstract": [
        {
          "text": "Identify and address issues in your app using the Xcode debugger, Xcode Organizer, Metal debugger, and Instruments.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/debugging",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Debugging",
      "type": "topic",
      "url": "/documentation/xcode/debugging"
    },
    "doc://com.apple.Xcode/documentation/Xcode/diagnosing-issues-using-crash-reports-and-device-logs": {
      "abstract": [
        {
          "text": "Use crash reports and device logs to debug app issues.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/diagnosing-issues-using-crash-reports-and-device-logs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Diagnosing issues using crash reports and device logs",
      "type": "topic",
      "url": "/documentation/xcode/diagnosing-issues-using-crash-reports-and-device-logs"
    },
    "doc://com.apple.Xcode/documentation/Xcode/examining-the-fields-in-a-crash-report#Diagnostic-messages": {
      "abstract": [],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/examining-the-fields-in-a-crash-report#Diagnostic-messages",
      "kind": "section",
      "title": "Diagnostic messages",
      "type": "topic",
      "url": "/documentation/xcode/examining-the-fields-in-a-crash-report#Diagnostic-messages"
    },
    "doc://com.apple.Xcode/documentation/Xcode/understanding-the-exception-types-in-a-crash-report": {
      "abstract": [
        {
          "text": "Learn what the exception type tells you about why your app crashed.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/understanding-the-exception-types-in-a-crash-report",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Understanding the exception types in a crash report",
      "type": "topic",
      "url": "/documentation/xcode/understanding-the-exception-types-in-a-crash-report"
    },
    "doc://com.apple.documentation/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/Dispatch"
    },
    "doc://com.apple.documentation/documentation/Swift/fatalError(_:file:line:)": {
      "abstract": [
        {
          "text": "Unconditionally prints a given message and stops execution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fatalError"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "message"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "attribute",
          "text": "@autoclosure "
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " = String(), "
        },
        {
          "kind": "externalParam",
          "text": "file"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s12StaticStringV",
          "text": "StaticString"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "keyword",
          "text": "#file"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "line"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "keyword",
          "text": "#line"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5NeverO",
          "text": "Never"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Swift/fatalError(_:file:line:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "fatalError(_:file:line:)",
      "type": "topic",
      "url": "/documentation/Swift/fatalError(_:file:line:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Exceptions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Xcode/documentation/Xcode/EXC_ARITHMETIC",
        "doc://com.apple.Xcode/documentation/Xcode/EXC_BAD_ACCESS",
        "doc://com.apple.Xcode/documentation/Xcode/SIGBUS",
        "doc://com.apple.Xcode/documentation/Xcode/SIGSEGV",
        "doc://com.apple.Xcode/documentation/Xcode/EXC_CRASH",
        "doc://com.apple.Xcode/documentation/Xcode/SIGABRT",
        "doc://com.apple.Xcode/documentation/Xcode/SIGKILL",
        "doc://com.apple.Xcode/documentation/Xcode/SIGQUIT",
        "doc://com.apple.Xcode/documentation/Xcode/SIGSYS",
        "doc://com.apple.Xcode/documentation/Xcode/SIGTERM",
        "doc://com.apple.Xcode/documentation/Xcode/EXC_GUARD",
        "doc://com.apple.Xcode/documentation/Xcode/EXC_RESOURCE"
      ],
      "title": "Exceptions"
    }
  ]
}
