{
  "abstract": [
    {
      "text": "A convenience method that creates and raises an exception.",
      "type": "text"
    }
  ],
  "documentVersion": 0,
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.documentation/documentation/foundation",
        "doc://com.apple.documentation/documentation/foundation/errors_and_exceptions",
        "doc://com.apple.documentation/documentation/foundation/nsexception"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.documentation/documentation/foundation/nsexception/1569524-raise"
  },
  "kind": "symbol",
  "legacy_identifier": 1569524,
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSException(cm)raise:format:",
    "modules": [
      {
        "name": "Foundation"
      }
    ],
    "parent": {
      "title": "NSException"
    },
    "platforms": [
      {
        "current": "18.4",
        "introducedAt": "2.0",
        "name": "iOS"
      },
      {
        "current": "18.4",
        "introducedAt": "2.0",
        "name": "iPadOS"
      },
      {
        "current": "18.4",
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "current": "15.4",
        "introducedAt": "10.0",
        "name": "macOS"
      },
      {
        "current": "18.4",
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "current": "2.4",
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "current": "11.4",
        "introducedAt": "2.0",
        "name": "watchOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "clm",
    "title": "raise:format:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "kind": "keyword",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ")"
            },
            {
              "kind": "identifier",
              "text": "raise:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsexceptionname",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSExceptionName",
              "text": "NSExceptionName"
            },
            {
              "kind": "text",
              "text": ")"
            },
            {
              "kind": "internalParam",
              "text": "name"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "format:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " *"
            },
            {
              "kind": "text",
              "text": ")"
            },
            {
              "kind": "internalParam",
              "text": "format"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "internalParam",
              "text": "..."
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "languages": [
        "occ"
      ],
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The name of the exception.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "name"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A human-readable message string (that is, the exception reason) with conversion specifications for the variable arguments that follow. ",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "format,"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Variable information to be inserted into the formatted exception reason (in the manner of ",
                  "type": "text"
                },
                {
                  "code": "printf",
                  "type": "codeVoice"
                },
                {
                  "text": ").",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "..."
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The user-defined information is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " for the generated exception object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation": {
      "identifier": "doc://com.apple.documentation/documentation/foundation",
      "kind": "symbol",
      "role": "collection",
      "title": "Foundation",
      "type": "topic",
      "url": "/documentation/foundation"
    },
    "doc://com.apple.documentation/documentation/foundation/errors_and_exceptions": {
      "identifier": "doc://com.apple.documentation/documentation/foundation/errors_and_exceptions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Errors and Exceptions",
      "type": "topic",
      "url": "/documentation/foundation/errors_and_exceptions"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception": {
      "abstract": [
        {
          "text": "An object that represents a special condition that interrupts the normal flow of program execution.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSException",
      "type": "topic",
      "url": "/documentation/foundation/nsexception"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1409498-raise": {
      "abstract": [
        {
          "text": "Creates and raises an exception with the specified name, reason, and arguments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "raise:format:arguments:"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1409498-raise",
      "kind": "symbol",
      "role": "symbol",
      "title": "raise:format:arguments:",
      "type": "topic",
      "url": "/documentation/foundation/nsexception/1409498-raise"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1414506-initwithname": {
      "abstract": [
        {
          "text": "Initializes and returns a newly allocated exception object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithName:reason:userInfo:"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1414506-initwithname",
      "kind": "symbol",
      "role": "symbol",
      "title": "initWithName:reason:userInfo:",
      "type": "topic",
      "url": "/documentation/foundation/nsexception/1414506-initwithname"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1416135-raise": {
      "abstract": [
        {
          "text": "Raises the receiver, causing program flow to jump to the local exception handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "raise"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1416135-raise",
      "kind": "symbol",
      "role": "symbol",
      "title": "raise",
      "type": "topic",
      "url": "/documentation/foundation/nsexception/1416135-raise"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1569524-raise": {
      "abstract": [
        {
          "text": "A convenience method that creates and raises an exception.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "raise:format:"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1569524-raise",
      "kind": "symbol",
      "role": "symbol",
      "title": "raise:format:",
      "type": "topic",
      "url": "/documentation/foundation/nsexception/1569524-raise"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1569530-exceptionwithname": {
      "abstract": [
        {
          "text": "Creates and returns an exception object .",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "exceptionWithName:reason:userInfo:"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1569530-exceptionwithname",
      "kind": "symbol",
      "role": "symbol",
      "title": "exceptionWithName:reason:userInfo:",
      "type": "topic",
      "url": "/documentation/foundation/nsexception/1569530-exceptionwithname"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexceptionname": {
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexceptionname",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSExceptionName",
      "type": "topic",
      "url": "/documentation/foundation/nsexceptionname"
    },
    "doc://com.apple.documentation/documentation/foundation/nsstring": {
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/nsexception/1569530-exceptionwithname",
        "doc://com.apple.documentation/documentation/foundation/nsexception/1409498-raise",
        "doc://com.apple.documentation/documentation/foundation/nsexception/1414506-initwithname",
        "doc://com.apple.documentation/documentation/foundation/nsexception/1416135-raise"
      ],
      "title": "Creating and Raising an NSException Object"
    }
  ],
  "variants": [
    {
      "paths": [
        "documentation/foundation/nsexception/1569524-raise"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
