{
  "abstract": [
    {
      "text": "The error object representing the last authentication failure.",
      "type": "text"
    }
  ],
  "documentVersion": 0,
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.documentation/documentation/foundation",
        "doc://com.apple.documentation/documentation/foundation/url_loading_system",
        "doc://com.apple.documentation/documentation/foundation/urlauthenticationchallenge"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.documentation/documentation/foundation/urlauthenticationchallenge/1413033-error"
  },
  "kind": "symbol",
  "legacy_identifier": 1413033,
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSURLAuthenticationChallenge(py)error",
    "fragments": [
      {
        "kind": "text",
        "text": "var "
      },
      {
        "kind": "identifier",
        "text": "error"
      },
      {
        "kind": "text",
        "text": ": (any Error)?"
      }
    ],
    "modules": [
      {
        "name": "Foundation"
      }
    ],
    "parent": {
      "title": "URLAuthenticationChallenge"
    },
    "platforms": [
      {
        "current": "18.4",
        "introducedAt": "2.0",
        "name": "iOS"
      },
      {
        "current": "18.4",
        "introducedAt": "2.0",
        "name": "iPadOS"
      },
      {
        "current": "18.4",
        "introducedAt": "13.1",
        "name": "Mac Catalyst"
      },
      {
        "current": "15.4",
        "introducedAt": "10.2",
        "name": "macOS"
      },
      {
        "current": "18.4",
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "current": "2.4",
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "current": "11.4",
        "introducedAt": "2.0",
        "name": "watchOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "instp",
    "title": "error"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "error"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "text",
              "text": "(any "
            },
            {
              "identifier": "doc://com.apple.Swift/documentation/Swift/Error",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5ErrorP",
              "text": "Error"
            },
            {
              "kind": "text",
              "text": ")?"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This value is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " if the protocol doesnâ€™t use errors to indicate an authentication failure.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.Swift/documentation/Swift/Error": {
      "identifier": "doc://com.apple.Swift/documentation/Swift/Error",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/swift/error"
    },
    "doc://com.apple.documentation/documentation/foundation": {
      "identifier": "doc://com.apple.documentation/documentation/foundation",
      "kind": "symbol",
      "role": "collection",
      "title": "Foundation",
      "type": "topic",
      "url": "/documentation/foundation"
    },
    "doc://com.apple.documentation/documentation/foundation/url_loading_system": {
      "identifier": "doc://com.apple.documentation/documentation/foundation/url_loading_system",
      "kind": "article",
      "role": "collectionGroup",
      "title": "URL Loading System",
      "type": "topic",
      "url": "/documentation/foundation/url_loading_system"
    },
    "doc://com.apple.documentation/documentation/foundation/urlauthenticationchallenge": {
      "abstract": [
        {
          "text": "A challenge from a server requiring authentication from the client.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/urlauthenticationchallenge",
      "kind": "symbol",
      "role": "symbol",
      "title": "URLAuthenticationChallenge",
      "type": "topic",
      "url": "/documentation/foundation/urlauthenticationchallenge"
    },
    "doc://com.apple.documentation/documentation/foundation/urlauthenticationchallenge/1413033-error": {
      "abstract": [
        {
          "text": "The error object representing the last authentication failure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": (any Error)?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/urlauthenticationchallenge/1413033-error",
      "kind": "symbol",
      "role": "symbol",
      "title": "error",
      "type": "topic",
      "url": "/documentation/foundation/urlauthenticationchallenge/1413033-error"
    },
    "doc://com.apple.documentation/documentation/foundation/urlauthenticationchallenge/1414978-failureresponse": {
      "abstract": [
        {
          "text": "The URL response object representing the last authentication failure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "failureResponse"
        },
        {
          "kind": "text",
          "text": ": URLResponse?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/urlauthenticationchallenge/1414978-failureresponse",
      "kind": "symbol",
      "role": "symbol",
      "title": "failureResponse",
      "type": "topic",
      "url": "/documentation/foundation/urlauthenticationchallenge/1414978-failureresponse"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "generated": false,
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/urlauthenticationchallenge/1414978-failureresponse"
      ],
      "title": "Related Documentation"
    }
  ],
  "variants": [
    {
      "paths": [
        "documentation/foundation/nsurlauthenticationchallenge/1413033-error"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    },
    {
      "paths": [
        "documentation/foundation/urlauthenticationchallenge/1413033-error"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
